# Generated by Django 4.2.1 on 2023-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1001, max_length=10),
            preserve_default=False,
        ),
    ]
