# Generated by Django 4.2.1 on 2023-05-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_date',
        ),
    ]
